services:
  php:
    container_name: php
    build: 
      dockerfile: docker/php/Dockerfile
    volumes:
      - './:/var/www/html/'

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - './:/var/www/html/' 
      - './docker/nginx/conf.d/:/etc/nginx/conf.d/'

  mysql:
    container_name: mysql
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app        # Nume baza de date
      MYSQL_USER: app            # Utilizator pentru baza de date
      MYSQL_PASSWORD: app        # Parolă pentru utilizator
    ports:
      - "3307:3306"
    volumes:
      - './docker/volume/mysql:/var/lib/mysql/'

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "9090:80"
    environment:
      PMA_HOST: mysql            # Numele serviciului MySQL
      PMA_PORT: 3306             # Portul intern MySQL din container

  redis:
   container_name: redis
   image: redis:latest
   ports:
    - "6380:6379"

